 
   version: '3.7'
   services:
     elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
       container_name: elasticsearch
       environment:
         - discovery.type=single-node
       networks:
         elk-network:
           ipv4_address: 172.22.0.2

     logstash:
       image: docker.elastic.co/logstash/logstash:7.10.1
       container_name: logstash
       volumes:
         - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
       networks:
         elk-network:
           ipv4_address: 172.22.0.3
       depends_on:
         - elasticsearch
       healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:9600"]
         interval: 30s
         timeout: 10s
         retries: 5

     kibana:
       image: docker.elastic.co/kibana/kibana:7.10.1
       container_name: kibana
       ports:
         - "5601:5601"
       networks:
         elk-network:
           ipv4_address: 172.22.0.4
       depends_on:
         - elasticsearch
       volumes:
         - ./kibana.yml:/usr/share/kibana/config/kibana.yml

     nginx:
       image: nginx
       container_name: nginx
       ports:
         - "8080:80"
       logging:
         driver: syslog
         options:
           syslog-address: "udp://172.22.0.3:5000"  # Use the static IP of Logstash
           tag: "{{.Name}}"
       networks:
         - elk-network
       depends_on:
         - logstash

   networks:
     elk-network:
       driver: bridge
       ipam:
         config:
           - subnet: 172.22.0.0/16
